# Ustawienia bazy danych PostgreSQL (dla Supabase) - zalecany Connection Pooler
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.qatzxomknwfabmyeyige
spring.datasource.password=nowehaslodobazypls
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# JWT Secret Key - In production, use environment variables!
application.security.jwt.secret-key=SzhkTWJaN0Jha1huMjVBdFdyZlJ2UGFqNlRzY1FtNEI0WEM5VnNmUyt4az0=
application.security.jwt.expiration=86400000

# File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
