# Database configuration using environment variables provided by Render
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.qatzxomknwfabmyeyige
spring.datasource.password=nowehaslodobazypls
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# JWT Secret Key from environment variable
application.security.jwt.secret-key=SzhkTWJaN0Jha1huMjVBdFdyZlJ2UGFqNlRzY1FtNEI0WEM5VnNmUyt4az0=
application.security.jwt.expiration=86400000

# File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Frontend URL from environment variable
application.frontend.url=${FRONTEND_URL:http://localhost:5173}