CREATE TABLE public.badges (
    id bigint NOT NULL,
    condition_type character varying(255),
    condition_value integer,
    description character varying(255) NOT NULL,
    icon character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);



ALTER TABLE public.badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    content character varying(500) NOT NULL,
    game_id character varying(255) NOT NULL,
    reported boolean NOT NULL,
    sender_id bigint NOT NULL,
    sender_username character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL
);



ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.friendships (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    receiver_wins integer NOT NULL,
    requester_wins integer NOT NULL,
    status character varying(255) NOT NULL,
    receiver_id bigint NOT NULL,
    requester_id bigint NOT NULL,
    CONSTRAINT friendships_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying])::text[])))
);



ALTER TABLE public.friendships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friendships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.hints (
    id bigint NOT NULL,
    description text NOT NULL,
    room_id bigint NOT NULL
);



ALTER TABLE public.hints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.path_enrollments (
    path_id bigint NOT NULL,
    user_id bigint NOT NULL,
    enrolled_at timestamp(6) without time zone NOT NULL
);



CREATE TABLE public.path_rooms (
    path_id bigint NOT NULL,
    room_id bigint NOT NULL,
    sort_order integer NOT NULL
);



CREATE TABLE public.paths (
    id bigint NOT NULL,
    banner_data bytea,
    banner_mime character varying(120),
    banner_url text,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    title character varying(120) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);



ALTER TABLE public.paths ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paths_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.room_files (
    id bigint NOT NULL,
    data oid,
    file_name character varying(255),
    file_type character varying(255),
    room_id bigint
);



ALTER TABLE public.room_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.room_tasks (
    id bigint NOT NULL,
    answer character varying(255),
    content text NOT NULL,
    question text,
    sort_order integer NOT NULL,
    title character varying(255) NOT NULL,
    room_id bigint NOT NULL
);



ALTER TABLE public.room_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.rooms (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text NOT NULL,
    difficulty character varying(255) NOT NULL,
    flag character varying(255) NOT NULL,
    points integer NOT NULL,
    requires_vpn boolean NOT NULL,
    room_type character varying(16) NOT NULL,
    short_description character varying(255),
    solutions_count integer NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT rooms_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying, 'INSANE'::character varying])::text[]))),
    CONSTRAINT rooms_points_check CHECK ((points >= 0)),
    CONSTRAINT rooms_room_type_check CHECK (((room_type)::text = ANY ((ARRAY['CTF'::character varying, 'PATH'::character varying])::text[]))),
    CONSTRAINT rooms_solutions_count_check CHECK ((solutions_count >= 0))
);



ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.user_badges (
    id bigint NOT NULL,
    earned_at timestamp(6) without time zone NOT NULL,
    badge_id bigint NOT NULL,
    user_id bigint NOT NULL
);



ALTER TABLE public.user_badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.user_completed_tasks (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone NOT NULL,
    task_id bigint NOT NULL,
    user_id bigint NOT NULL
);



ALTER TABLE public.user_completed_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_completed_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.user_solved_rooms (
    id bigint NOT NULL,
    solved_at timestamp(6) without time zone NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL
);



ALTER TABLE public.user_solved_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_solved_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.user_unlocked_hints (
    id bigint NOT NULL,
    hint_id bigint NOT NULL,
    user_id bigint NOT NULL
);



ALTER TABLE public.user_unlocked_hints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_unlocked_hints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.user_weekly_active_time (
    user_id bigint NOT NULL,
    week_key character varying(16) NOT NULL,
    seconds integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);



CREATE TABLE public.users (
    id bigint NOT NULL,
    bio text,
    created_at timestamp(6) without time zone NOT NULL,
    elo integer DEFAULT 500 NOT NULL,
    email character varying(255) NOT NULL,
    last_solved_date date,
    muted_until timestamp(6) without time zone,
    password character varying(255) NOT NULL,
    points integer NOT NULL,
    role character varying(255) NOT NULL,
    streak integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(20) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'EXPERT'::character varying])::text[])))
);



ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY public.badges
    ADD CONSTRAINT badges_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.hints
    ADD CONSTRAINT hints_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.path_enrollments
    ADD CONSTRAINT path_enrollments_pkey PRIMARY KEY (path_id, user_id);



ALTER TABLE ONLY public.path_rooms
    ADD CONSTRAINT path_rooms_pkey PRIMARY KEY (path_id, room_id);



ALTER TABLE ONLY public.paths
    ADD CONSTRAINT paths_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.room_files
    ADD CONSTRAINT room_files_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.room_tasks
    ADD CONSTRAINT room_tasks_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT uk1x3gugupa5w402iklhs2e4ai6 UNIQUE (title);



ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT uk5r2v5xn0il3p8dc9nf4v94r2b UNIQUE (user_id, badge_id);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);



ALTER TABLE ONLY public.user_solved_rooms
    ADD CONSTRAINT ukab78h5i5n5rip2pvk5qmfg9ow UNIQUE (user_id, room_id);



ALTER TABLE ONLY public.badges
    ADD CONSTRAINT ukcuebofvgkgi4g9fxde2kmpr1h UNIQUE (name);



ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT ukgcmm7x3ou06bugneuc6la2cmf UNIQUE (requester_id, receiver_id);



ALTER TABLE ONLY public.user_unlocked_hints
    ADD CONSTRAINT ukh4vmp7u8sw73ev22tgwkbealu UNIQUE (user_id, hint_id);



ALTER TABLE ONLY public.room_files
    ADD CONSTRAINT ukqr30elu9rrm7fqj6vxgev6f6 UNIQUE (room_id);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);



ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT user_badges_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.user_completed_tasks
    ADD CONSTRAINT user_completed_tasks_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.user_solved_rooms
    ADD CONSTRAINT user_solved_rooms_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.user_unlocked_hints
    ADD CONSTRAINT user_unlocked_hints_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.user_weekly_active_time
    ADD CONSTRAINT user_weekly_active_time_pkey PRIMARY KEY (user_id, week_key);



ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.room_tasks
    ADD CONSTRAINT fk5ahni1hck7oxhbg4rwv3gu6v2 FOREIGN KEY (room_id) REFERENCES public.rooms(id);



ALTER TABLE ONLY public.user_unlocked_hints
    ADD CONSTRAINT fk7pfnos3ymaq52chaixdwah8p3 FOREIGN KEY (hint_id) REFERENCES public.hints(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT fkas6bp8so5n3pfcqtfxt72e1ii FOREIGN KEY (requester_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.hints
    ADD CONSTRAINT fkaskr7bl48ur0tsdw5bpfnakrm FOREIGN KEY (room_id) REFERENCES public.rooms(id);



ALTER TABLE ONLY public.room_files
    ADD CONSTRAINT fkccgcxl6ogai8eb6g6vmuodyld FOREIGN KEY (room_id) REFERENCES public.rooms(id);



ALTER TABLE ONLY public.user_solved_rooms
    ADD CONSTRAINT fkibive0lek5ogvjk9tj3f48xxx FOREIGN KEY (room_id) REFERENCES public.rooms(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.user_unlocked_hints
    ADD CONSTRAINT fkie0vpjds93e1dmivpy8oe6mf0 FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;



ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT fkk6e00pguaij0uke6xr81gt045 FOREIGN KEY (badge_id) REFERENCES public.badges(id);



ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT fkpk7w2cj6m9n224ny2t7fhi47 FOREIGN KEY (receiver_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.user_badges
    ADD CONSTRAINT fkr46ah81sjymsn035m4ojstn5s FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.user_solved_rooms
    ADD CONSTRAINT fksmn9dl6e3s818ky75h6nmcwly FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
