CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(20) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    bio text,
    role varchar(255) NOT NULL,
    points integer NOT NULL,
    streak integer NOT NULL,
    elo integer NOT NULL DEFAULT 500,
    last_solved_date date,
    muted_until timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_lowercase CHECK (email = lower(email)),
    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'ADMIN', 'EXPERT')),
    CONSTRAINT ck_users_points CHECK (points >= 0),
    CONSTRAINT ck_users_streak CHECK (streak >= 0)
);

CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username));
CREATE INDEX idx_users_points ON users (points DESC);
CREATE INDEX idx_users_elo ON users (elo DESC);

CREATE TABLE badges (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    icon varchar(255) NOT NULL,
    condition_type varchar(255) NOT NULL,
    condition_value integer NOT NULL,
    CONSTRAINT pk_badges PRIMARY KEY (id),
    CONSTRAINT uq_badges_name UNIQUE (name),
    CONSTRAINT ck_badges_condition_type CHECK (condition_type IN ('POINTS', 'STREAK', 'SOLVED_COUNT', 'FRIENDS_COUNT')),
    CONSTRAINT ck_badges_condition_value CHECK (condition_value >= 0)
);

CREATE TABLE user_badges (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    badge_id bigint NOT NULL,
    earned_at timestamp(6) NOT NULL,
    CONSTRAINT pk_user_badges PRIMARY KEY (id),
    CONSTRAINT uq_user_badges_user_badge UNIQUE (user_id, badge_id),
    CONSTRAINT fk_user_badges_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_badges_badge FOREIGN KEY (badge_id) REFERENCES badges (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_badges_badge ON user_badges (badge_id);

CREATE TABLE rooms (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title varchar(255) NOT NULL,
    description text NOT NULL,
    short_description varchar(255),
    difficulty varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    points integer NOT NULL,
    flag varchar(255) NOT NULL,
    solutions_count integer NOT NULL,
    requires_vpn boolean NOT NULL,
    room_type varchar(16) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (id),
    CONSTRAINT uq_rooms_title UNIQUE (title),
    CONSTRAINT ck_rooms_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD', 'INSANE')),
    CONSTRAINT ck_rooms_room_type CHECK (room_type IN ('CTF', 'PATH')),
    CONSTRAINT ck_rooms_points CHECK (points >= 0),
    CONSTRAINT ck_rooms_solutions_count CHECK (solutions_count >= 0)
);

CREATE TABLE room_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title varchar(255) NOT NULL,
    content text NOT NULL,
    question text,
    answer varchar(255),
    room_id bigint NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT pk_room_tasks PRIMARY KEY (id),
    CONSTRAINT fk_room_tasks_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    CONSTRAINT ck_room_tasks_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_room_tasks_room_sort ON room_tasks (room_id, sort_order);

CREATE TABLE hints (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    description text NOT NULL,
    room_id bigint NOT NULL,
    CONSTRAINT pk_hints PRIMARY KEY (id),
    CONSTRAINT fk_hints_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE
);

CREATE INDEX idx_hints_room ON hints (room_id);

CREATE TABLE room_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    file_name varchar(255),
    file_type varchar(255),
    data bytea,
    room_id bigint NOT NULL,
    CONSTRAINT pk_room_files PRIMARY KEY (id),
    CONSTRAINT uq_room_files_room UNIQUE (room_id),
    CONSTRAINT fk_room_files_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE
);

CREATE TABLE paths (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title varchar(120) NOT NULL,
    description text,
    banner_url text,
    banner_data bytea,
    banner_mime varchar(120),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT pk_paths PRIMARY KEY (id)
);

CREATE TABLE path_rooms (
    path_id bigint NOT NULL,
    room_id bigint NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT pk_path_rooms PRIMARY KEY (path_id, room_id),
    CONSTRAINT fk_path_rooms_path FOREIGN KEY (path_id) REFERENCES paths (id) ON DELETE CASCADE,
    CONSTRAINT fk_path_rooms_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    CONSTRAINT ck_path_rooms_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_path_rooms_path_sort ON path_rooms (path_id, sort_order);
CREATE INDEX idx_path_rooms_room ON path_rooms (room_id);

CREATE TABLE path_enrollments (
    user_id bigint NOT NULL,
    path_id bigint NOT NULL,
    enrolled_at timestamp(6) NOT NULL,
    CONSTRAINT pk_path_enrollments PRIMARY KEY (user_id, path_id),
    CONSTRAINT fk_path_enrollments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_path_enrollments_path FOREIGN KEY (path_id) REFERENCES paths (id) ON DELETE CASCADE
);

CREATE INDEX idx_path_enrollments_path ON path_enrollments (path_id);

CREATE TABLE user_solved_rooms (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    room_id bigint NOT NULL,
    solved_at timestamp(6) NOT NULL,
    CONSTRAINT pk_user_solved_rooms PRIMARY KEY (id),
    CONSTRAINT uq_user_solved_rooms_user_room UNIQUE (user_id, room_id),
    CONSTRAINT fk_user_solved_rooms_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_solved_rooms_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_solved_rooms_user_solved_at ON user_solved_rooms (user_id, solved_at DESC);
CREATE INDEX idx_user_solved_rooms_room ON user_solved_rooms (room_id);

CREATE TABLE user_completed_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    task_id bigint NOT NULL,
    completed_at timestamp(6) NOT NULL,
    CONSTRAINT pk_user_completed_tasks PRIMARY KEY (id),
    CONSTRAINT uq_user_completed_tasks_user_task UNIQUE (user_id, task_id),
    CONSTRAINT fk_user_completed_tasks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_completed_tasks_task FOREIGN KEY (task_id) REFERENCES room_tasks (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_completed_tasks_task ON user_completed_tasks (task_id);

CREATE TABLE user_unlocked_hints (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    hint_id bigint NOT NULL,
    CONSTRAINT pk_user_unlocked_hints PRIMARY KEY (id),
    CONSTRAINT uq_user_unlocked_hints_user_hint UNIQUE (user_id, hint_id),
    CONSTRAINT fk_user_unlocked_hints_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_unlocked_hints_hint FOREIGN KEY (hint_id) REFERENCES hints (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_unlocked_hints_hint ON user_unlocked_hints (hint_id);

CREATE TABLE friendships (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    requester_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    status varchar(255) NOT NULL,
    requester_wins integer NOT NULL,
    receiver_wins integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT pk_friendships PRIMARY KEY (id),
    CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friendships_receiver FOREIGN KEY (receiver_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_friendships_status CHECK (status IN ('PENDING', 'ACCEPTED')),
    CONSTRAINT ck_friendships_not_self CHECK (requester_id <> receiver_id),
    CONSTRAINT ck_friendships_wins CHECK (requester_wins >= 0 AND receiver_wins >= 0)
);

CREATE UNIQUE INDEX uq_friendships_pair ON friendships (least(requester_id, receiver_id), greatest(requester_id, receiver_id));
CREATE INDEX idx_friendships_receiver ON friendships (receiver_id);

CREATE TABLE chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    game_id varchar(255) NOT NULL,
    sender_id bigint NOT NULL,
    sender_username varchar(255) NOT NULL,
    content varchar(500) NOT NULL,
    reported boolean NOT NULL,
    sent_at timestamp(6) NOT NULL,
    CONSTRAINT pk_chat_messages PRIMARY KEY (id),
    CONSTRAINT fk_chat_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_chat_messages_game_sent_at ON chat_messages (game_id, sent_at);
CREATE INDEX idx_chat_messages_sender ON chat_messages (sender_id);
CREATE INDEX idx_chat_messages_reported_sent_at ON chat_messages (sent_at DESC) WHERE reported;

CREATE TABLE user_weekly_active_time (
    user_id bigint NOT NULL,
    week_key varchar(16) NOT NULL,
    seconds integer NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT pk_user_weekly_active_time PRIMARY KEY (user_id, week_key),
    CONSTRAINT fk_user_weekly_active_time_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_weekly_active_time_seconds CHECK (seconds >= 0)
);
