CREATE TABLE path_chapters (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    path_id bigint NOT NULL,
    title varchar(120) NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT pk_path_chapters PRIMARY KEY (id),
    CONSTRAINT fk_path_chapters_path FOREIGN KEY (path_id) REFERENCES paths (id) ON DELETE CASCADE,
    CONSTRAINT ck_path_chapters_title CHECK (btrim(title) <> ''),
    CONSTRAINT ck_path_chapters_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_path_chapters_path_sort ON path_chapters (path_id, sort_order);

CREATE TABLE chapter_rooms (
    room_id bigint NOT NULL,
    chapter_id bigint NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT pk_chapter_rooms PRIMARY KEY (room_id),
    CONSTRAINT fk_chapter_rooms_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE CASCADE,
    CONSTRAINT fk_chapter_rooms_chapter FOREIGN KEY (chapter_id) REFERENCES path_chapters (id) ON DELETE CASCADE,
    CONSTRAINT ck_chapter_rooms_sort_order CHECK (sort_order >= 0)
);

CREATE INDEX idx_chapter_rooms_chapter_sort ON chapter_rooms (chapter_id, sort_order);

INSERT INTO path_chapters (path_id, title, sort_order, created_at, updated_at)
SELECT id, 'Rozdział 1', 0, now(), now()
FROM paths;

INSERT INTO chapter_rooms (room_id, chapter_id, sort_order)
SELECT owner.room_id,
       chapter.id,
       (row_number() OVER (PARTITION BY owner.path_id ORDER BY owner.sort_order, owner.room_id) - 1)::integer
FROM (
    SELECT DISTINCT ON (room_id) room_id, path_id, sort_order
    FROM path_rooms
    ORDER BY room_id, path_id
) owner
JOIN path_chapters chapter ON chapter.path_id = owner.path_id;

DROP TABLE path_rooms;
